### ISSUE TITLE
Мой отчет о результатах комита

### ISSUE THREAD

**Issue by UMSF-K13-1-Braslavskyi** [UMSF-K13-1-Braslavskyi/K13-1-Braslavskyi-MainProject#1]
![image](https://cloud.githubusercontent.com/assets/19633125/15634694/cf4e7550-25d2-11e6-84be-8e003d7b284d.png)
создал изменение с сообщением "init"
![image](https://cloud.githubusercontent.com/assets/19633125/15634701/0ecad89a-25d3-11e6-97ca-b39b436fd1dc.png)
для того чтобы синхронизировать пришлось создать новую ветвь "mastero"

**Comment by smoktii-igov** [comment]
ок
